admin:
    backendroles:
        - admin
    host:
        - "*"
    users:
        - elastic
        - kibana
        - logstash

kibana:
    backendroles:
        - kibana_user
    host:
        - "*"
    users:
        - kibana

logstash:
    backendroles:
        - logstash_user
    host:
        - "*"
    users:
        - logstash

beats:
    backendroles:
        - beats_user
    host:
        - "*"
    users:
        - beats
