path:
  data: /data/data
  logs: /data/log
  plugins: /data/plugins
  work: /data/work
network:
   host: 0.0.0.0
discovery.zen.minimum_master_node: 1
xpack:
  security:
    authc:
      realms:
        native1:
          type: native
          order: 0
