path:
  data: /data/lib
  logs: /data/log
  plugins: /data/plugins
  work: /data/work
network:
   host: 0.0.0.0
discovery.zen.minimum_master_node: 1
xpack:
  security:
    authc:
      realms:
        native1:
          type: native
          order: 0
#discovery.zen.ping.unicast.hosts:
#   - 192.168.1.10:9300
#   - 192.168.1.11 
#   - seeds.mydomain.com 